from __future__ import annotations

DOWNLOAD_STALL_TIMEOUT_DEFAULT_SECONDS = 600
DOWNLOAD_ARCHIVE_TTL_DEFAULT_SECONDS = 24 * 60 * 60
DOWNLOAD_HTTP_MAX_RETRIES_HARD_LIMIT_DEFAULT = 8
HITOMI_LISTING_MAX_GALLERIES_DEFAULT = 500
CIVITAI_IMAGE_MAX_RESOURCE_JOBS_DEFAULT = 30
JOB_LOG_MAX_CHARS_DEFAULT = 200_000
MAX_CONCURRENT_DOWNLOADS_HARD_LIMIT_DEFAULT = 12
MEDIA_CACHE_MAX_BYTES_DEFAULT = 0
MEDIA_CACHE_TTL_DEFAULT_SECONDS = 30 * 24 * 60 * 60
MEDIA_TRANSCODE_MAX_CONCURRENT_DEFAULT = 1
PROCESS_OUTPUT_QUEUE_MAX_LINES_DEFAULT = 1000
QUEUE_PROVIDER_COOLDOWN_MAX_DEFAULT_SECONDS = 2
QUEUE_PROVIDER_COOLDOWN_MIN_DEFAULT_SECONDS = 2
QUEUE_PER_PROVIDER_LIMIT_HARD_LIMIT_DEFAULT = 4
YT_DLP_DEFAULT_FORMAT = "best[ext=mp4][vcodec^=avc1]/best[ext=mp4]/best"
