from __future__ import annotations

DOWNLOAD_STALL_TIMEOUT_DEFAULT_SECONDS = 600
QUEUE_PROVIDER_COOLDOWN_MAX_DEFAULT_SECONDS = 2
QUEUE_PROVIDER_COOLDOWN_MIN_DEFAULT_SECONDS = 2
YT_DLP_DEFAULT_FORMAT = "best[ext=mp4][vcodec^=avc1]/best[ext=mp4]/best"
